# Generated by Django 4.1.3 on 2023-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_test_field2_test_field3'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='field4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
