# Generated by Django 4.1.3 on 2023-01-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_mesta_spektakl_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesta',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
